### ISSUE TITLE
Provide xsd for custom-fields

### ISSUE THREAD

**Issue by powli** [shopware/AppBundle#19]
#12 will bring the ability to generate the manifest file from the used attributes in the App. Custom fields however are imported from a XML file that needs to be compatible with the [custom fields definition](https://github.com/shopware/platform/blob/trunk/src/Core/Framework/App/Manifest/Schema/manifest-1.0.xsd#L153-L157) in the xsd for the manifest file.
It would be nice to have a `.xsd` file for the custom fields alone, if implementation should stay that way.

**Comment by shyim** [comment]
see https://github.com/shopware/AppBundle/pull/25#issuecomment-1539453329
